[package]
name = "ember"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.64"
modular-bitfield = "0.11.2"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"

[lib]
crate-type = ["cdylib", "rlib"]
